### ISSUE TITLE
Release patch version?

### ISSUE THREAD

**Issue by fschutt** [RazrFalcon/usvg#24]
Because I needed the improved error handling in https://github.com/RazrFalcon/usvg/commit/280f77fbd03f1bf83852b3080fdd93c24579e97e I currently depend on the github source directly. Would it be possible to release a patch version, like `0.2.1` on crates.io? Thanks in advance.

**Comment by RazrFalcon** [comment]
0.2.1 isn't possible, because it contains breaking changes. And I'm not planned to make a new release.

At the moment, it's in an experimental state since in depends on git dependencies too. So I'm not ready for 0.3.0 either.

Not sure what can be done here. I have to check that I can release `svgdom` first and then I probably can release `usvg` too. But I didn't touch them in months. I quite busy at the moment, so I can't make any real changes to the code.

I will see what can be done tomorrow. Or if you not in the hurry, in a few months.

**Comment by fschutt** [comment]
Yeah, I'm not in a hurry, but thanks for looking into it.

**Comment by RazrFalcon** [comment]
Well, then it's better to wait. I don't have a time at the moment to validate everything, and there were a lot of changes. I don't want to release a broken version and I don't have a time to fix it.

**Comment by RazrFalcon** [comment]
Done. I've basically frozen the current changes. There are a lot of changes in the `svgdom`, but they should not affect you.
